export const projects = [
  {
    id: 5,
    name: "Good Living",
    created: "09/23",
    desc: "This is an home-goods ecommerce website where you can buy furniture,appliances etc. The main goal of this project was to integrate redux-persist and stripe payments",
    stack: [
      "React",
      "HTML",
      "CSS",
      "JavaScript",
      "Redux-Persist",
      "Stripe API",
    ],
    img: "media/goodliving-thumbnail.png",
    url: "https://good-living.netlify.app",
    git: "https://github.com/Gwazza23/good-living",
  },
  {
    id: 4,
    name: "Music Nexus",
    created: "08/23",
    desc: "The aim of this project is to make a spotify profile overview/analyzer by using the Spotify API, however the underlying goal of the project was to learning how to incorporate Oauth2.0 in order to access the API resources.",
    stack: [
      "React",
      "HTML",
      "CSS",
      "JavaScript",
      "ChartJS",
      "Cypress",
      "Spotify API",
      "OAuth2.0",
    ],
    img: "media/musicnexus-thumbnail.png",
    url: "https://musicnexus.vercel.app",
    git: "https://github.com/Gwazza23/musicnexus",
    note: "The current app is still under development mode of the spotify API so it cannot be accessed by personal accounts unless it is whitelisted first, to bypass this problem please use the credentials given below to log in and use the website \nE-mail - tester145@gmail.com\nPassword - example145",
  },
  {
    id: 3,
    name: "House of Fashion",
    created: "07/23",
    desc: "This project is an online e-commerce website designed to mimic a fully functional online shopping platform. The goal in creating this project was to create a full stack application ( front-end, back-end, database ) and mesh each component in order to provide users with a complete online shopping experience.",
    stack: [
      "React",
      "HTML",
      "CSS",
      "JavaScript",
      "NodeJs",
      "Express",
      "SQL",
      "Cypress",
      "Framer",
    ],
    img: "/media/houseoffashion-thumbnail.png",
    url: "https://houseoffashion.netlify.app",
    git: "https://github.com/Gwazza23/HOF",
    note: "The backend server and database are been hosted on free to use containers so please allow 10-20 seconds for the servers to wake up",
  },
  {
    id: 2,
    name: "CineVerse",
    created: "06/23",
    desc: "The aim of this project is to make a movie database website powered by TMDB API, that allows users to explore and discover movies. The personal goal of this project is to further reinforce the front-end react skills from the previous project.",
    stack: ["React", "HTML", "CSS", "JavaScript", "Framer motion"],
    img: "/media/cineverse-thumbnail.png",
    url: "https://cverse.netlify.app/",
    git: "https://github.com/Gwazza23/CineVerse",
  },
  {
    id: 1,
    name: "Reddit.min",
    created: "04/23",
    desc: "Reddit.min is a simplified reddit clone that aims to recreate the core functionality of Reddit by utilising Reddit API. This project serves as my first front-end endeavor. The goal of this project was to build strong foundation in my react & GitHub skills.",
    stack: ["React", "HTML", "CSS", "JavaScript"],
    img: "/media/redditmin-thumbnail.png",
    url: "https://redditmin.netlify.app",
    git: "https://github.com/Gwazza23/Reddit-App",
  },
];
